name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare publish directory
        run: |
          # Create the distribution directory
          mkdir -p dist

          # Copy all static assets
          cp index.html style.css app.js data.js ui.js dist/

          # Create the secret config file directly in the destination
          echo "${{ secrets.FIREBASE_CONFIG_JS }}" > dist/firebase-config.js
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist