name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Debug Secret Access
        run: echo "Creating firebase-config.js file..."
        env:
          FIREBASE_CONFIG_JS: ${{ secrets.FIREBASE_CONFIG_JS }}

      - name: Create Firebase Config from Secret
        run: echo "$FIREBASE_CONFIG_JS" > firebase-config.js
        env:
          FIREBASE_CONFIG_JS: ${{ secrets.FIREBASE_CONFIG_JS }}

      - name: Verify Firebase Config File
        run: |
          echo "Listing files to verify firebase-config.js exists:"
          ls -la

      - name: Prepare publish directory
        run: |
          mkdir -p dist
          cp *.html *.css *.js dist/
        shell: bash

      - name: Move Firebase Config to Deployment Directory
        run: mv firebase-config.js ./dist/

      - name: Verify Deployment Files
        run: |
          echo "Listing files in deployment directory to verify firebase-config.js exists:"
          ls -la ./dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist