name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create Firebase config file
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_JS }}" > firebase-config.js
        shell: bash

      - name: Prepare publish directory
        run: |
          mkdir -p dist
          cp *.html *.css *.js dist/
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist